# Generated by Django 4.1.2 on 2022-10-15 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto_aut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aut_placa', models.CharField(max_length=7)),
                ('aut_color', models.CharField(max_length=20)),
                ('aut_imagen', models.URLField()),
                ('aut_modelo', models.CharField(max_length=50)),
                ('aut_descripcion', models.TextField()),
                ('aut_fecadquisicion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Documento_doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_tipo', models.URLField()),
                ('doc_fecdoc', models.DateField()),
                ('doc_fecregistro', models.DateTimeField(auto_now_add=True)),
                ('doc_fecmodificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InsCodigo_inc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inc_codigo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='InsNombre_ino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ino_nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Instrumento_ins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ins_unidad', models.CharField(max_length=5)),
                ('ins_codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_foundation.inscodigo_inc')),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentoXAuto_ixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_foundation.auto_aut')),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_foundation.instrumento_ins')),
            ],
        ),
        migrations.CreateModel(
            name='Marca_mar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mar_nombre', models.CharField(max_length=20)),
                ('mar_year', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroDatos_rda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rda_fecha', models.DateField()),
                ('rda_hora', models.TimeField()),
                ('ixa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_foundation.instrumentoxauto_ixa')),
            ],
        ),
        migrations.CreateModel(
            name='Taller_tal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tal_nombre', models.CharField(max_length=30)),
                ('tal_ubicaciondir', models.CharField(max_length=300)),
                ('tal_puntuacion', models.IntegerField(choices=[(5, 'Excelente'), (4, 'Muy Bueno'), (3, 'Bueno'), (2, 'Malo'), (1, 'Muy Malo')])),
                ('tal_ruc', models.CharField(max_length=8)),
                ('tal_descripcion', models.TextField()),
                ('tal_ubicacion_lat', models.FloatField()),
                ('tal_ubicacion_lon', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoMantenimiento_tman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tman_nombre', models.CharField(max_length=50)),
                ('tman_descripcion', models.TextField()),
                ('tman_precio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_usu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usu_nombres', models.CharField(max_length=50)),
                ('usu_email', models.EmailField(max_length=100)),
                ('usu_password', models.CharField(max_length=50)),
                ('usu_celular', models.CharField(max_length=8)),
                ('usu_fecregistro', models.DateTimeField(auto_now_add=True)),
                ('usu_fecmodificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroManual_rma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rma_nombre', models.CharField(max_length=100)),
                ('rma_descripcion', models.TextField()),
                ('rma_fecha', models.DateField()),
                ('rma_hora', models.TimeField()),
                ('rma_fecregistro', models.DateTimeField(auto_now_add=True)),
                ('rma_fecmodificacion', models.DateTimeField(auto_now=True)),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_foundation.auto_aut')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroError_rer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rer_nombre', models.CharField(max_length=100)),
                ('rer_descripcion', models.TextField()),
                ('rer_fecha', models.DateField()),
                ('rer_hora', models.TimeField()),
                ('rer_fecregistro', models.DateTimeField(auto_now_add=True)),
                ('rer_fecmodificacion', models.DateTimeField(auto_now=True)),
                ('registro_datos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_foundation.registrodatos_rda')),
                ('registro_manual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_foundation.registromanual_rma')),
            ],
        ),
        migrations.CreateModel(
            name='Mantenimiento_man',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('man_fecha', models.DateField()),
                ('man_proxfecha', models.DateField()),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_foundation.auto_aut')),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_foundation.taller_tal')),
                ('tipo_matenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_foundation.tipomantenimiento_tman')),
            ],
        ),
        migrations.AddField(
            model_name='inscodigo_inc',
            name='inc_nombre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_foundation.insnombre_ino'),
        ),
        migrations.CreateModel(
            name='DocumentoXAuto_dxa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_foundation.auto_aut')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_foundation.documento_doc')),
            ],
        ),
        migrations.AddField(
            model_name='auto_aut',
            name='aut_marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_foundation.marca_mar'),
        ),
        migrations.AddField(
            model_name='auto_aut',
            name='aut_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_foundation.usuario_usu'),
        ),
    ]
