# Generated by Django 4.1.2 on 2022-10-20 16:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('back_foundation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto_aut',
            name='aut_fecmodificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='auto_aut',
            name='aut_fecregistro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auto_aut',
            name='aut_marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marca', to='back_foundation.marca_mar'),
        ),
        migrations.AlterField(
            model_name='auto_aut',
            name='aut_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='back_foundation.usuario_usu'),
        ),
    ]
