# Generated by Django 4.1.2 on 2022-11-20 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_foundation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
