# Generated by Django 4.1.2 on 2022-10-26 17:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_foundation', '0002_remove_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='imagen',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dm8aqmori/image/upload/v1666805714/usuario_tcf7ys.png', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='auto_aut',
            name='aut_imagen',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/dm8aqmori/image/upload/v1666805846/autoIcono_ljytgv.png', max_length=255, null=True, verbose_name='image'),
        ),
    ]
