# Generated by Django 4.1.2 on 2022-11-25 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_foundation', '0002_remove_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroerror_rer',
            name='registro_manual',
        ),
        migrations.RemoveField(
            model_name='registroerror_rer',
            name='rer_fecha',
        ),
        migrations.RemoveField(
            model_name='registroerror_rer',
            name='rer_hora',
        ),
    ]
