# Generated by Django 4.1.2 on 2022-10-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_foundation', '0003_user_imagen_alter_auto_aut_aut_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='admin', max_length=255),
        ),
    ]
