# Generated by Django 4.1.2 on 2022-11-26 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_foundation', '0003_remove_registroerror_rer_registro_manual_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroerror_rer',
            name='rer_fecmodificacion',
        ),
    ]
