# Generated by Django 4.1.2 on 2022-10-26 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_foundation', '0005_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
