# Generated by Django 4.1.2 on 2022-10-26 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_foundation', '0010_remove_user_imagen_user_us_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='us_imagen',
            new_name='imagen',
        ),
    ]
