# Generated by Django 4.1.2 on 2022-10-28 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_foundation', '0011_rename_us_imagen_user_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='admin', max_length=250),
        ),
    ]
