# Generated by Django 4.1.2 on 2022-11-02 14:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('back_foundation', '0012_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumento_ins',
            name='ins_nombre',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='instrumentoxauto_ixa',
            name='ixa_fecinstalacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instrumentoxauto_ixa',
            name='ixa_fecmodificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='instrumento_ins',
            name='ins_codigo',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='InsCodigo_inc',
        ),
        migrations.DeleteModel(
            name='InsNombre_ino',
        ),
    ]
