# Generated by Django 4.1.2 on 2022-11-02 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_foundation', '0012_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
