# Generated by Django 4.1.2 on 2022-11-02 20:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_foundation', '0013_remove_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto_aut',
            name='aut_imagen',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/dm8aqmori/image/upload/v1666805846/autoIcono_ljytgv.png', max_length=255, null=True, verbose_name='aut_imagen'),
        ),
    ]
