# Generated by Django 4.1.2 on 2022-11-03 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_foundation', '0013_instrumento_ins_ins_nombre_and_more'),
        ('back_foundation', '0014_alter_auto_aut_aut_imagen'),
    ]

    operations = [
    ]
