# Generated by Django 4.1.2 on 2022-11-20 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_foundation', '0015_merge_20221103_1550'),
        ('back_foundation', '0015_merge_20221105_1258'),
    ]

    operations = [
    ]
