# Generated by Django 4.1.3 on 2022-11-18 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_foundation', '0015_merge_20221103_1550'),
        ('back_foundation', '0015_merge_20221105_1258'),
    ]

    operations = [
    ]
